### ISSUE TITLE
Kamihr Drifts homepoint not found 

### ISSUE THREAD

**Issue by lcreed** [SammehFFXI/FFXIAddons#2]
homepoint lua works great for every hp I've tried besides Kamihr.

**Comment by SammehFFXI** [comment]
Hey there - I'm sorry I never noticed this open issue.  

the really odd thing about this one.. and not sure why this one... but if you type out "Kamihr Drifts 1" it works fine.  If you tab it out - it doesn't.. not sure why.

-Sam

**Comment by lcreed** [comment]
Ahh, I didn't try typing it out.  That is weird.  

Thanks for the great luas!
